### ISSUE TITLE
Missing paginator on optimized builds

### ISSUE THREAD

**Issue by Neraste** [Nadeflore/dakara-client-web#22]
With `--optimize-minimize`, `libraryName` (and maybe other variables) is not defined and messes with the paginator.

**Comment by Nadeflore** [comment]
Fixed in commit df900346bdeed7ed9c44ec7c33e5dff78b5ff982

This bug was caused by libraryPage checking the name of his children,
but in minified build, the names are replaced, hence the bug.
Fixed by adding a static method on classes returning the class name, and using it to retrieve the name
