### ISSUE TITLE
Make Field component manage different input types

### ISSUE THREAD

**Issue by Nadeflore** [Nadeflore/dakara-client-web#24]

**Comment by Neraste** [comment]
Handled by commits 87f71fea49403e54e8bdb909b4cfb97c684dc835, 064beb2385111235a60746756cfc813be0a3348b, 0bfaf32ce0e6b08522ad81f920b7c855c85116d5, 4d4d75054679c2796d428f29e04e86c86914041c, 5df854f27c79c95e2e4c69fd2d9965296e56a98e and 28edb2d9f97da4c77308086bf8639f12f618843a.
